### ISSUE TITLE
Initial Route Name 

### ISSUE THREAD

**Issue by KashyapProdigy** [NitishQuovantis/AnimatingBottomBar#3]
My Tabbar is working fine 
Everything is configured as per docs

Just help me on how to set initial Route 

Because I tried few things 
But it always set initial Route to first screen registered in Navigation screens object

Thank you from future 👍

**Comment by NitishQuovantis** [comment]
@KashyapProdigy right now the only way to set initial route is to pass it as the first screen in the configuration object. I will update the library to also cater this use-case. I will update it in few days.

**Comment by KashyapProdigy** [comment]
Mostly apps have a setup of 
5 or 3 bottom tabs 

In which Home screen is usually center one 
Home screen as first tab is not appropriate approach of design.

Will be looking out for your fix .

**Comment by NitishQuovantis** [comment]
I understand your use-case and will try to update it asap.

**Comment by NitishQuovantis** [comment]
Support for initial route name has been added. Please update library for 1.0.5.
